# Change these first
owner: yangbvv # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: blog
    url: https://blog.yangbvv.repl.co
  - name: nav
    url: https://nav.yangbvv.repl.co
  - name: alist
    url: https://alist.yangbvv.repl.co
  - name: reader
    url: https://reader.yangbvv.repl.co
  - name: drpy
    url: https://drpy.yangbvv.repl.co
  - name: uptime-kuma
    url: https://uptime-kuma.yangbvv.repl.co
  - name: v2
    url: https://v2.yangbvv.repl.co
  - name: v3
    url: https://v3.yangbvv.repl.co
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
